name: Artifact Build

on:
  push:
  workflow_dispatch:

env:
  REACT_APP_LOGIN_URL: ${{ env.REACT_APP_LOGIN_URL }}
  REACT_APP_COOKIE_DOMAIN: ${{ env.REACT_APP_COOKIE_DOMAIN }}
  REACT_APP_COOKIE_NAME: ${{ env.REACT_APP_COOKIE_NAME }}
  REACT_APP_BACKEND_URL: ${{ env.REACT_APP_BACKEND_URL }}
  GQL_SCHEMA_TOKEN: ${{ secrets.GQL_SCHEMA_TOKEN }}
  REACT_APP_NEXTAUTH_SECRET: ${{ secrets.REACT_APP_NEXTAUTH_SECRET }}

jobs:
  build:
    if: startsWith(github.event.commits[0].message, 'MKZ-')
    name: Build Web Extension and store artifact

    strategy:
      fail-fast: false
      matrix:
        platform: [ macos-latest, ubuntu-latest ]
    runs-on: ${{ matrix.platform }}

    steps:
      - uses: actions/checkout@v1
      - uses: actions/setup-node@v1
        with:
          node-version: 18
      - name: Build
        run: |
          yarn install --immutable --immutable-cache --check-cache
          yarn build
      - name: Setup XCode (macos only)
        if: matrix.platform == 'macos-latest'
        uses: maxim-lobanov/setup-xcode@v1
        with:
          xcode-version: latest
      - name: Build with XCode (macos only)
        if: matrix.platform == 'macos-latest'
        run: |
          xcrun safari-web-extension-converter ./build
          xcodebuild -project ./Markurz/Markurz.xcodeproj -scheme Markurz\ (macOS) -destination "generic/platform=macOS" build
      - name: Zip Folder
        run: zip -r build.zip build
      - uses: actions/upload-artifact@v3
        with:
          name: build
          path: build.zip
