name: Artifact Build

on:
  push:
  workflow_dispatch:

jobs:
  build:
    if: startsWith(github.event.commits[0].message, 'MKZ-')
    name: Build Web Extension and store artifact

    strategy:
      fail-fast: false
      matrix:
        platform: [ macos-latest, ubuntu-latest ]
    runs-on: ${{ matrix.platform }}

    steps:
      - uses: actions/checkout@v1
      - uses: actions/setup-node@v3
        with:
          node-version: 18
      - name: Build
        run: |
          yarn install --immutable --immutable-cache --check-cache
          yarn build
      - name: Build with XCode (macos only)
        if: matrix.platform == 'macos-latest'
        uses: actions/setup-xcode@v1
        with:
          xcode-version: 14.x
        run: |
          xcrun safari-web-extension-converter ./build
          xcodebuild -project ./Markurz/Markurz.xcodeproj -scheme Markurz\ (macOS) -destination "generic/platform=macOS" build
      - name: Zip Folder
        run: zip -r build.zip build
      - uses: actions/upload-artifact@v3
        with:
          name: build
          path: build.zip
