name: Publish Package
on:
  workflow_dispatch:
  push:
    branches:
      - master

jobs:
  publish-gpr:
    runs-on: ubuntu-latest
    environment: ${{ github.ref == 'refs/heads/main' && 'Production' || 'Development' }}
    env:
      REACT_APP_LOGIN_URL: ${{ vars.REACT_APP_LOGIN_URL }}
      REACT_APP_COOKIE_DOMAIN: ${{ vars.REACT_APP_COOKIE_DOMAIN }}
      REACT_APP_COOKIE_NAME: ${{ vars.REACT_APP_COOKIE_NAME }}
      REACT_APP_BACKEND_URL: ${{ vars.REACT_APP_BACKEND_URL }}
      GQL_SCHEMA_TOKEN: ${{ secrets.GQL_SCHEMA_TOKEN }}
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 18
          registry-url: https://registry.npmjs.org/
      - run: yarn install --immutable --immutable-cache --check-cache
      - run: git config --global user.email "$GITHUB_ACTOR@users.noreply.github.com" && git config --global user.name "$GITHUB_ACTOR"
      - run: yarn version --minor
      - run: mv ./src/rollup.ts ./src/index.ts
      - run: yarn generate
      - run: yarn rollup
      - run: yarn pack
      - run: tar -ztvf *.tgz
      - run: mv ./src/index.ts ./src/rollup.ts
      - run: git push --tags && git push
      - run: yarn publish *.tgz
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
