name: Publish Testing

on:
  push:
    tags:
      - 'v((?![a-zA-Z]).)*'
  workflow_dispatch:

env:
  FOLDER_NAME: build_${{ github.ref == 'refs/heads/main' && 'prod' || 'dev' }}

jobs:
  build:
    name: Publish web extension testing
    runs-on: ubuntu-latest
    environment: Production
    env:
      REACT_APP_LOGIN_URL: ${{ vars.REACT_APP_LOGIN_URL }}
      REACT_APP_COOKIE_DOMAIN: ${{ vars.REACT_APP_COOKIE_DOMAIN }}
      REACT_APP_COOKIE_NAME: ${{ vars.REACT_APP_COOKIE_NAME }}
      REACT_APP_BACKEND_URL: ${{ vars.REACT_APP_BACKEND_URL }}
      GQL_SCHEMA_TOKEN: ${{ secrets.GQL_SCHEMA_TOKEN }}
      REACT_APP_NEXTAUTH_SECRET: ${{ secrets.REACT_APP_NEXTAUTH_SECRET }}

    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Build
        run: |
          yarn install --immutable --immutable-cache --check-cache
          yarn build

      - name: Zip Folder
        run: cd build && zip -r ../${{ env.FOLDER_NAME }}.zip "."

      - name: Publish to Chrome Store
        uses: mnao305/chrome-extension-upload@v4.0.1
        with:
          file-path: ${{ env.FOLDER_NAME }}.zip
          extension-id: lnbfijiimlnnpjmfgmfdmdmlobadcloo
          client-id: ${{ secrets.CLIENT_ID }}
          client-secret: ${{ secrets.CLIENT_SECRET }}
          refresh-token: ${{ secrets.REFRESH_TOKEN }}
          publish: false

      - name: Publish to Edge store
        uses: hocgin/action-edge-addone-upload@main
        with:
          product_id: ${{ secrets.EDGE_PRODUCT_ID }}
          client_id: ${{ secrets.EDGE_CLIENT_ID }}
          client_secret: ${{ secrets.EDGE_CLIENT_SECRET }}
          access_token_url: ${{ secrets.EDGE_ACCESS_TOKEN_URL }}
          addone_file: ${{ env.FOLDER_NAME }}.zip

      - uses: actions/upload-artifact@v3
        with:
          name: ${{ env.FOLDER_NAME }}
          path: ${{ env.FOLDER_NAME }}.zip
