name: Publish Package
on:
  workflow_dispatch:
  push:
    branches:
      - master

jobs:
  publish-gpr:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 18
          registry-url: https://registry.npmjs.org/
      - run: yarn install
      - run: git config --global user.email "$GITHUB_ACTOR@users.noreply.github.com" && git config --global user.name "$GITHUB_ACTOR"
      - run: yarn version --minor
      - run: mv ./src/rollup.ts ./src/index.ts
      - run: yarn rollup
      - run: yarn pack
      - run: tar -ztvf *.tgz
      - run: mv ./src/index.ts ./src/rollup.ts
      - run: git push --tags && git push
      - run: yarn publish *.tgz
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
